#!/usr/bin/env python
from daemonize import startstop
from agent import main
from utils.load_config import load_global_config

from sys import stderr as sys_stderr

config = load_global_config() 
ofile = config.get('ofile')
pfile = config.get('pfile')

startstop(stdout=ofile, 
          stderr=ofile, 
          pidfile=pfile)
main()

