#!/usr/bin/env python
from daemonize import startstop
from agent import main
from utils.load_config import load_global_config

from sys import stderr as sys_stderr

startstop(stdout='/dev/null', 
          stderr=sys_stderr, 
          pidfile='/tmp/monagent.pid')
main()

