#!/usr/bin/env python
from daemonize import startstop
import mon_agent


if __name__ == "__main__":
    ofile = mon_agent.global_config['ofile']
    pfile = mon_agent.global_config['pfile']
    startstop(stdout=ofile, pidfile=pfile)
    mon_agent.startup()
    #heartbeat(('192.168.226.63', 20060))
